name: ğŸ¦€ Rust
on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4

      - name: ğŸŒ™ Install Nightly toolchain
        run: rustup install nightly

      - name: ğŸ› ï¸ Install Clippy
        working-directory: wasm/
        run: rustup component add clippy

      - name: ğŸ¦€ Clippy
        working-directory: wasm/
        run: cargo clippy

      - name: ğŸ” Test
        working-directory: wasm/
        run: cargo test

      - name: ğŸ“– Doc
        working-directory: wasm/
        run: cargo doc --no-deps --target wasm32-unknown-unknown
