name: ğŸ¦€ Rust
on: [push]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4

      - name: ğŸŒ™ Install Nightly toolchain
        run: rustup install nightly

      - name: ğŸ•¸ï¸ Add wasm target
        run: rustup +nightly target add wasm32-unknown-unknown

      - name: ğŸ› ï¸ Install Clippy
        run: rustup +nightly component add clippy

      - name: ğŸ¦€ Clippy
        working-directory: wasm/
        run: cargo clippy

      - name: ğŸ” Test
        working-directory: wasm/
        run: cargo test

      - name: ğŸ“– Doc
        working-directory: wasm/
        run: cargo doc --no-deps --target wasm32-unknown-unknown

      - name: âš™ï¸ Setup Pages
        uses: actions/configure-pages@v4

      - name: â¬†ï¸ Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "wasm/target/wasm32-unknown-unknown/doc"

      - name: ğŸš€ Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
